import React, { useState } from 'react';
import { AIMode, AIResponse } from '../types';
import { createFirestoreDocument } from '../lib/firebase';
import { Sparkles, Bolt, Brain, Send, Save, Check, Loader2, FileText, Lightbulb } from 'lucide-react';

interface AIPromptPlaygroundProps {
  userId: string | null;
  onDocumentCreated?: () => void;
}

export const AIPromptPlayground: React.FC<AIPromptPlaygroundProps> = ({ userId, onDocumentCreated }) => {
  const [prompt, setPrompt] = useState('');
  const [mode, setMode] = useState<AIMode>('general');
  const [loading, setLoading] = useState(false);
  const [response, setResponse] = useState<AIResponse | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [savingToDb, setSavingToDb] = useState(false);
  const [savedSuccess, setSavedSuccess] = useState(false);

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!prompt.trim()) return;

    setLoading(true);
    setError(null);
    setResponse(null);
    setSavedSuccess(false);

    const startTime = Date.now();
    let endpoint = '/api/gemini/general';
    if (mode === 'fast') endpoint = '/api/gemini/fast';
    if (mode === 'thinking') endpoint = '/api/gemini/thinking';

    try {
      const res = await fetch(endpoint, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt }),
      });

      const data = await res.json();
      if (!res.ok) {
        throw new Error(data.error || 'Failed to generate AI response');
      }

      const endTime = Date.now();
      setResponse({
        text: data.text,
        model: data.model,
        latencyMs: endTime - startTime,
      });
    } catch (err: any) {
      console.error('AI Generation Error:', err);
      setError(err.message || 'Error executing AI model request.');
    } finally {
      setLoading(false);
    }
  };

  const handleSaveToFirestore = async () => {
    if (!userId) {
      alert('Please sign in with Google to save documents to your Firestore database.');
      return;
    }
    if (!response || !response.text) return;

    setSavingToDb(true);
    try {
      const title = prompt.length > 40 ? `${prompt.substring(0, 40)}...` : prompt;
      await createFirestoreDocument(
        userId,
        title,
        prompt,
        mode === 'thinking' ? 'Deep AI Research' : mode === 'fast' ? 'Quick AI Note' : 'AI Generated',
        `Generated by ${response.model} (${response.latencyMs}ms):\n\n${response.text}`
      );
      setSavedSuccess(true);
      if (onDocumentCreated) onDocumentCreated();
      setTimeout(() => setSavedSuccess(false), 4000);
    } catch (err: any) {
      console.error('Error saving to Firestore:', err);
      alert('Failed to save to Firestore: ' + err.message);
    } finally {
      setSavingToDb(false);
    }
  };

  return (
    <div className="bento-card shadow-lg space-y-4">
      <div className="flex items-center justify-between pb-3 border-b border-slate-700/40">
        <div className="flex items-center space-x-2.5">
          <div className="w-9 h-9 rounded-2xl bg-blue-500/10 border border-blue-500/30 flex items-center justify-center text-blue-400">
            <Sparkles className="w-4 h-4" />
          </div>
          <div>
            <h2 className="font-bold text-base text-slate-100 tracking-tight flex items-center gap-2">
              <span>EduLocker AI Assistant</span>
              <span className="text-[10px] text-blue-400 font-mono bg-blue-500/10 px-2 py-0.5 rounded-full border border-blue-500/30">Gemini Powered</span>
            </h2>
            <p className="text-xs text-slate-400">Auto-parse certificates, analyze transcripts & generate academic summaries</p>
          </div>
        </div>
      </div>

      {/* Model Selection Tabs */}
      <div className="grid grid-cols-3 gap-2">
        <button
          type="button"
          onClick={() => setMode('fast')}
          className={`flex flex-col items-center justify-center p-3 rounded-2xl border text-xs transition-all duration-200 font-medium ${
            mode === 'fast'
              ? 'bg-amber-500/10 border-amber-500/40 text-amber-300 shadow-md'
              : 'bg-slate-900/60 border-slate-700/30 text-slate-400 hover:text-slate-200 hover:border-slate-600/50'
          }`}
        >
          <div className="flex items-center space-x-1.5 font-bold mb-0.5">
            <Bolt className="w-3.5 h-3.5 text-amber-400" />
            <span>Fast Mode</span>
          </div>
          <span className="text-[10px] text-slate-500 font-mono">gemini-3.1-flash-lite</span>
        </button>

        <button
          type="button"
          onClick={() => setMode('general')}
          className={`flex flex-col items-center justify-center p-3 rounded-2xl border text-xs transition-all duration-200 font-medium ${
            mode === 'general'
              ? 'bg-blue-500/10 border-blue-500/40 text-blue-300 shadow-md'
              : 'bg-slate-900/60 border-slate-700/30 text-slate-400 hover:text-slate-200 hover:border-slate-600/50'
          }`}
        >
          <div className="flex items-center space-x-1.5 font-bold mb-0.5">
            <Sparkles className="w-3.5 h-3.5 text-blue-400" />
            <span>General</span>
          </div>
          <span className="text-[10px] text-slate-500 font-mono">gemini-3.5-flash</span>
        </button>

        <button
          type="button"
          onClick={() => setMode('thinking')}
          className={`flex flex-col items-center justify-center p-3 rounded-2xl border text-xs transition-all duration-200 font-medium ${
            mode === 'thinking'
              ? 'bg-purple-500/10 border-purple-500/40 text-purple-300 shadow-md'
              : 'bg-slate-900/60 border-slate-700/30 text-slate-400 hover:text-slate-200 hover:border-slate-600/50'
          }`}
        >
          <div className="flex items-center space-x-1.5 font-bold mb-0.5">
            <Brain className="w-3.5 h-3.5 text-purple-400" />
            <span>High Thinking</span>
          </div>
          <span className="text-[10px] text-slate-500 font-mono">gemini-3.1-pro-preview</span>
        </button>
      </div>

      {/* Input Form */}
      <form onSubmit={handleGenerate} className="space-y-3">
        <div>
          <textarea
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            placeholder={
              mode === 'thinking'
                ? 'Ask a complex question requiring step-by-step reasoning or technical problem solving...'
                : mode === 'fast'
                ? 'Enter a prompt for instant, low-latency key takeaways or draft...'
                : 'Enter topic, question, or prompt for Gemini AI...'
            }
            rows={3}
            className="w-full bg-slate-950/80 border border-slate-700/40 rounded-2xl p-3.5 text-sm text-slate-200 placeholder-slate-500 focus:outline-none focus:border-blue-500/50 focus:ring-1 focus:ring-blue-500/50 resize-none font-sans"
          />
        </div>

        <div className="flex items-center justify-between">
          <div className="text-xs text-slate-400 flex items-center space-x-1.5 font-mono">
            <Lightbulb className="w-3.5 h-3.5 text-amber-400" />
            <span>
              {mode === 'thinking'
                ? 'Thinking Level: HIGH enabled'
                : mode === 'fast'
                ? 'Optimized for low-latency speed'
                : 'Balanced accuracy and response'}
            </span>
          </div>

          <button
            type="submit"
            disabled={loading || !prompt.trim()}
            className="flex items-center space-x-2 bg-blue-600 hover:bg-blue-500 text-white font-semibold text-xs px-5 py-2.5 rounded-full transition-all duration-200 disabled:opacity-50 disabled:cursor-not-allowed shadow-md shadow-blue-500/20 active:scale-95"
          >
            {loading ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                <span>Processing AI...</span>
              </>
            ) : (
              <>
                <Send className="w-4 h-4" />
                <span>Run Prompt</span>
              </>
            )}
          </button>
        </div>
      </form>

      {/* Error Message */}
      {error && (
        <div className="p-3 bg-rose-500/10 border border-rose-500/30 rounded-2xl text-rose-300 text-xs font-mono">
          {error}
        </div>
      )}

      {/* AI Output Response Box */}
      {response && (
        <div className="bg-slate-950/90 border border-slate-700/40 rounded-2xl p-4">
          <div className="flex items-center justify-between mb-2 pb-2 border-b border-slate-800">
            <div className="flex items-center space-x-2 text-xs font-mono text-slate-400">
              <span className="text-blue-400 font-bold">{response.model}</span>
              {response.latencyMs && (
                <span className="text-emerald-400 bg-emerald-500/10 px-2 py-0.5 rounded-full border border-emerald-500/30 font-semibold">
                  {response.latencyMs}ms
                </span>
              )}
            </div>

            <button
              onClick={handleSaveToFirestore}
              disabled={savingToDb || savedSuccess}
              className={`flex items-center space-x-1.5 text-xs px-3.5 py-1.5 rounded-full border font-semibold transition ${
                savedSuccess
                  ? 'bg-emerald-500/10 border-emerald-500/30 text-emerald-400'
                  : 'bg-blue-600/20 border-blue-500/30 text-blue-300 hover:bg-blue-600/30'
              }`}
            >
              {savingToDb ? (
                <Loader2 className="w-3.5 h-3.5 animate-spin" />
              ) : savedSuccess ? (
                <>
                  <Check className="w-3.5 h-3.5 text-emerald-400" />
                  <span>Saved to Firestore!</span>
                </>
              ) : (
                <>
                  <Save className="w-3.5 h-3.5" />
                  <span>Save to Firestore DB</span>
                </>
              )}
            </button>
          </div>

          <div className="text-sm text-slate-200 whitespace-pre-wrap leading-relaxed max-h-80 overflow-y-auto pr-1 font-sans">
            {response.text}
          </div>
        </div>
      )}
    </div>
  );

};
